2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=8e29cc4fe86a
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] db version v3.6.3
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] modules: none
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] build environment:
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-06-22T19:59:44.792+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0", port: 27017 }, processManagement: { fork: true }, storage: { dbPath: "/data/db" }, systemLog: { destination: "file", path: "/data/logs" } }
2019-06-22T19:59:44.792+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2019-06-22T19:59:44.792+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-06-22T19:59:44.792+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-06-22T19:59:44.792+0000 I STORAGE  [initandlisten] 
2019-06-22T19:59:44.792+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-06-22T19:59:44.792+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2019-06-22T19:59:44.792+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7454M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-06-22T19:59:45.719+0000 I STORAGE  [initandlisten] WiredTiger message [1561233585:719357][8:0x7f9e77b19f80], txn-recover: Main recovery loop: starting at 46/3328
2019-06-22T19:59:45.720+0000 I STORAGE  [initandlisten] WiredTiger message [1561233585:720030][8:0x7f9e77b19f80], txn-recover: Recovering log 46 through 47
2019-06-22T19:59:45.854+0000 I STORAGE  [initandlisten] WiredTiger message [1561233585:854081][8:0x7f9e77b19f80], txn-recover: Recovering log 47 through 47
2019-06-22T19:59:46.468+0000 I CONTROL  [initandlisten] 
2019-06-22T19:59:46.468+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-06-22T19:59:46.468+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-06-22T19:59:46.468+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-06-22T19:59:46.468+0000 I CONTROL  [initandlisten] 
2019-06-22T19:59:46.559+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-06-22T19:59:46.560+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-06-22T19:59:47.647+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:53982 #1 (1 connection now open)
2019-06-22T19:59:47.648+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:53982 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-22T19:59:47.649+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:53984 #2 (2 connections now open)
2019-06-22T19:59:47.649+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:53984 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-22T20:00:03.726+0000 I NETWORK  [conn1] end connection 127.0.0.1:53982 (1 connection now open)
2019-06-22T20:00:03.764+0000 I NETWORK  [conn2] end connection 127.0.0.1:53984 (0 connections now open)
2019-06-22T20:00:57.716+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:54248 #3 (1 connection now open)
2019-06-22T20:00:57.716+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:54250 #4 (2 connections now open)
2019-06-22T20:00:57.717+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:54248 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-22T20:00:57.717+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:54250 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-22T20:03:48.876+0000 I NETWORK  [conn3] end connection 127.0.0.1:54248 (1 connection now open)
2019-06-22T20:03:48.910+0000 I NETWORK  [conn4] end connection 127.0.0.1:54250 (0 connections now open)
2019-06-22T20:03:49.408+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:54654 #5 (1 connection now open)
2019-06-22T20:03:49.408+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:54656 #6 (2 connections now open)
2019-06-22T20:03:49.409+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:54654 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-22T20:03:49.410+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:54656 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-22-generic" }, platform: "CPython 3.6.7.final.0" }
