2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=305eca1adf72
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] db version v3.6.3
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] modules: none
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] build environment:
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-06-11T04:54:10.865+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0", port: 27017 }, processManagement: { fork: true }, storage: { dbPath: "/data/db" }, systemLog: { destination: "file", path: "/data/logs" } }
2019-06-11T04:54:10.866+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2019-06-11T04:54:11.605+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-06-11T04:54:11.605+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-06-11T04:54:11.605+0000 I STORAGE  [initandlisten] 
2019-06-11T04:54:11.605+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-06-11T04:54:11.605+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2019-06-11T04:54:11.665+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7454M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-06-11T04:54:13.023+0000 I STORAGE  [initandlisten] WiredTiger message [1560228853:23369][8:0x7f8e77910f80], txn-recover: Main recovery loop: starting at 28/6912
2019-06-11T04:54:13.024+0000 I STORAGE  [initandlisten] WiredTiger message [1560228853:24003][8:0x7f8e77910f80], txn-recover: Recovering log 28 through 29
2019-06-11T04:54:13.190+0000 I STORAGE  [initandlisten] WiredTiger message [1560228853:190843][8:0x7f8e77910f80], txn-recover: Recovering log 29 through 29
2019-06-11T04:54:15.260+0000 I CONTROL  [initandlisten] 
2019-06-11T04:54:15.260+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-06-11T04:54:15.260+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-06-11T04:54:15.260+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-06-11T04:54:15.260+0000 I CONTROL  [initandlisten] 
2019-06-11T04:54:16.093+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-06-11T04:54:16.097+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-06-11T04:54:17.222+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2019-06-11T04:54:25.173+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:38990 #1 (1 connection now open)
2019-06-11T04:54:25.173+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:38990 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:54:25.176+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:38992 #2 (2 connections now open)
2019-06-11T04:54:25.176+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:38992 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:54:38.052+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:39020 #3 (3 connections now open)
2019-06-11T04:54:38.052+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:39020 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:56:40.848+0000 I NETWORK  [conn3] end connection 127.0.0.1:39020 (2 connections now open)
2019-06-11T04:56:40.848+0000 I NETWORK  [conn2] end connection 127.0.0.1:38992 (0 connections now open)
2019-06-11T04:56:40.848+0000 I NETWORK  [conn1] end connection 127.0.0.1:38990 (1 connection now open)
2019-06-11T04:56:41.315+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:39250 #4 (1 connection now open)
2019-06-11T04:56:41.316+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:39252 #5 (2 connections now open)
2019-06-11T04:56:41.317+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:39250 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:56:41.317+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:39252 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:57:05.930+0000 I NETWORK  [conn4] end connection 127.0.0.1:39250 (1 connection now open)
2019-06-11T04:57:05.965+0000 I NETWORK  [conn5] end connection 127.0.0.1:39252 (0 connections now open)
2019-06-11T04:57:06.445+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:39296 #6 (1 connection now open)
2019-06-11T04:57:06.446+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:39296 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T04:57:06.446+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:39298 #7 (2 connections now open)
2019-06-11T04:57:06.447+0000 I NETWORK  [conn7] received client metadata from 127.0.0.1:39298 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-11T05:01:18.411+0000 I NETWORK  [conn6] end connection 127.0.0.1:39296 (1 connection now open)
2019-06-11T05:01:18.451+0000 I NETWORK  [conn7] end connection 127.0.0.1:39298 (0 connections now open)
